---
# tasks file for datahub.datahub

- name: Setup and scaffold the database structure
  command: sh app/console app:setup
  args:
    chdir: /vagrant/datahub

- name: Load database fixtures
  command: sh app/console doctrine:mongodb:fixtures:load --append
  args:
    chdir: /vagrant/datahub
